version: "3.7"

services:
  mongodb:
    container_name: "mongodb"
    image: mongo:5.0.5
    hostname: mongodb
    ports:
      - 27017:27017

  express_student_service:
    container_name: "express_student_service"
    image: student-service:2.0.0
    build:
      context: ./student
      dockerfile: dockerfile

    hostname: express_student_service
    depends_on:
      - mongodb
